services:
  - type: web
    name: ytdrop
    env: node
    buildCommand: npm install && python3 -m pip install yt-dlp --user && python3 -m pip install ffmpeg-python --user
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: PATH
        value: /home/render/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin